/obj/structure/retail/clothing_store
	desc = "Purchase all the finest outfits.. Or don't wagie.."
	products_list = list(
		new /datum/data/vending_product("crimson red dress", /obj/item/clothing/under/vampire/primogen_toreador/female	,	350),
		new /datum/data/vending_product("black dress", /obj/item/clothing/under/vampire/business,	250),
		new /datum/data/vending_product("black gown", /obj/item/clothing/under/vampire/gown_black,	250),
		new /datum/data/vending_product("white gown", /obj/item/clothing/under/vampire/gown_white,	250),
		new /datum/data/vending_product("black shawl", /obj/item/clothing/suit/vampire/shawl_black,	250),
		new /datum/data/vending_product("white shawl", /obj/item/clothing/suit/vampire/shawl_white,	250),
		new /datum/data/vending_product("leather pants", /obj/item/clothing/under/vampire/leatherpants,	200),
		new /datum/data/vending_product("fancy gray suit", /obj/item/clothing/under/vampire/fancy_gray,	150),
		new /datum/data/vending_product("fancy red suit", /obj/item/clothing/under/vampire/fancy_red,	150),
		new /datum/data/vending_product("black luxury suit", /obj/item/clothing/under/vampire/ventrue,	50),
		new /datum/data/vending_product("black luxury suit skirt", /obj/item/clothing/under/vampire/ventrue/female,	50),
		new /datum/data/vending_product("white buisness suit", /obj/item/clothing/under/vampire/office,	50),
		new /datum/data/vending_product("black overcoat", /obj/item/clothing/under/vampire/rich,	45),
		new /datum/data/vending_product("burgundy suit", /obj/item/clothing/under/vampire/tremere,	35),
		new /datum/data/vending_product("burgundy suit skirt", /obj/item/clothing/under/vampire/tremere/female,	35),
		new /datum/data/vending_product("plain black suit",	 /obj/item/clothing/under/vampire/suit,	50),
		new /datum/data/vending_product("plain black suitskirt",	 /obj/item/clothing/under/vampire/suit/female,	50),
		new /datum/data/vending_product("plain red suit",	 /obj/item/clothing/under/vampire/sheriff,	80),
		new /datum/data/vending_product("plain red suitskirt",	 /obj/item/clothing/under/vampire/sheriff/female,	80),
		new /datum/data/vending_product("plain blue suit",	 /obj/item/clothing/under/vampire/clerk,	90),
		new /datum/data/vending_product("plain blue suitskirt",	 /obj/item/clothing/under/vampire/clerk/female,	90),
		new /datum/data/vending_product("brown suit",	 /obj/item/clothing/under/vampire/archivist,	60),
		new /datum/data/vending_product("brown suitskirt",	 /obj/item/clothing/under/vampire/archivist/female,	60),
		new /datum/data/vending_product("flamboyant outfit", /obj/item/clothing/under/vampire/toreador,	30),
		new /datum/data/vending_product("female flamboyant outfit", /obj/item/clothing/under/vampire/toreador/female,	30),
		new /datum/data/vending_product("purple and black outfit", /obj/item/clothing/under/vampire/sexy,	25),
		new /datum/data/vending_product("slick jacket", /obj/item/clothing/under/vampire/slickback, 25),
		new /datum/data/vending_product("classic bomber jacket", /obj/item/clothing/suit/vampire/bomber_jacket_classic,	90),
		new /datum/data/vending_product("gray bomber jacket", /obj/item/clothing/suit/vampire/bomber_jacket_gray,	90),
		new /datum/data/vending_product("tracksuit", /obj/item/clothing/under/vampire/sport,	25),
		new /datum/data/vending_product("grimey pants", /obj/item/clothing/under/vampire/malkavian,	20),
		new /datum/data/vending_product("odd Goth schoolgirl attire", /obj/item/clothing/under/vampire/malkavian/female,	20),
		new /datum/data/vending_product("gothic clothes", /obj/item/clothing/under/vampire/gothic,	20),
		new /datum/data/vending_product("gothic attire", /obj/item/clothing/under/vampire/brujah,	20),
		new /datum/data/vending_product("female punk attire ", /obj/item/clothing/under/vampire/brujah/female,	20),
		new /datum/data/vending_product("pentagram shirt", /obj/item/clothing/under/vampire/baali,	20),
		new /datum/data/vending_product("pentagram skirt", /obj/item/clothing/under/vampire/baali/female,	20),
		new /datum/data/vending_product("punk outfit", /obj/item/clothing/under/vampire/emo,	20),
		new /datum/data/vending_product("red hipster outfit", /obj/item/clothing/under/vampire/red,	20),
		new /datum/data/vending_product("messy shirt", /obj/item/clothing/under/vampire/bouncer,	15),
		new /datum/data/vending_product("blue overalls", /obj/item/clothing/under/vampire/mechanic,	20),
		new /datum/data/vending_product("black overalls", /obj/item/clothing/under/vampire/graveyard, 20),
		new /datum/data/vending_product("black grunge outfit", /obj/item/clothing/under/vampire/black,	20),
		new /datum/data/vending_product("gimp outfit", /obj/item/clothing/under/vampire/nosferatu,	15),
		new /datum/data/vending_product("female gimp outfit", /obj/item/clothing/under/vampire/nosferatu/female,	15),
		new /datum/data/vending_product("rugged attire", /obj/item/clothing/under/vampire/gangrel,	15),
		new /datum/data/vending_product("female rugged attire", /obj/item/clothing/under/vampire/gangrel/female,	15),
		new /datum/data/vending_product("yellow sleeveless shirt", /obj/item/clothing/under/vampire/larry,	15),
		new /datum/data/vending_product("white sleeveless shirt", /obj/item/clothing/under/vampire/bandit,	15),
		new /datum/data/vending_product("white turtleneck", /obj/item/clothing/under/vampire/turtleneck_white,	15),
		new /datum/data/vending_product("black turtleneck", /obj/item/clothing/under/vampire/turtleneck_black,	15),
		new /datum/data/vending_product("red turtleneck", /obj/item/clothing/under/vampire/turtleneck_red,	15),
		new /datum/data/vending_product("navy turtleneck", /obj/item/clothing/under/vampire/turtleneck_navy,	15),
		new /datum/data/vending_product("biker outfit", /obj/item/clothing/under/vampire/biker,	15),
		new /datum/data/vending_product("burlesque outfit", /obj/item/clothing/under/vampire/burlesque,	15),
		new /datum/data/vending_product("daisy dukes", /obj/item/clothing/under/vampire/burlesque/daisyd,	10),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/vampire,	10),
		new /datum/data/vending_product("brown shoes", /obj/item/clothing/shoes/vampire/brown,	10),
		new /datum/data/vending_product("white shoes", /obj/item/clothing/shoes/vampire/white,	10),
		new /datum/data/vending_product("black boots", /obj/item/clothing/shoes/vampire/jackboots,	10),
		new /datum/data/vending_product("work boots", /obj/item/clothing/shoes/vampire/jackboots/work,	10),
		new /datum/data/vending_product("sneakers", /obj/item/clothing/shoes/vampire/sneakers,	10),
		new /datum/data/vending_product("red sneakers", /obj/item/clothing/shoes/vampire/sneakers/red,	10),
		new /datum/data/vending_product("high heels", /obj/item/clothing/shoes/vampire/heels,	35),
		new /datum/data/vending_product("red high heels", /obj/item/clothing/shoes/vampire/heels/red,	35),
		new /datum/data/vending_product("scaly shoes", /obj/item/clothing/shoes/vampire/businessscaly,	35),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/vampire/businessblack,	35),
		new /datum/data/vending_product("metal tip shoes", /obj/item/clothing/shoes/vampire/businesstip,	50),
		new /datum/data/vending_product("purple fur coat", /obj/item/clothing/suit/vampire/slickbackcoat,	500),
		new /datum/data/vending_product("too much fancy jacket", /obj/item/clothing/suit/vampire/majima_jacket,	100),
		new /datum/data/vending_product("labcoat", /obj/item/clothing/suit/vampire/labcoat,	75),
		new /datum/data/vending_product("fancy gray jacket", /obj/item/clothing/suit/vampire/fancy_gray,	50),
		new /datum/data/vending_product("fancy red jacket", /obj/item/clothing/suit/vampire/fancy_red,	50),
		new /datum/data/vending_product("black trenchcoat", /obj/item/clothing/suit/vampire/trench,	45),
		new /datum/data/vending_product("brown trenchcoat", /obj/item/clothing/suit/vampire/trench/alt,	35),
		new /datum/data/vending_product("brown coat", /obj/item/clothing/suit/vampire/coat,	15),
		new /datum/data/vending_product("green coat", /obj/item/clothing/suit/vampire/coat/alt,	15),
		new /datum/data/vending_product("jacket", /obj/item/clothing/suit/vampire/jacket,	15),
		new /datum/data/vending_product("black coat", /obj/item/clothing/suit/vampire/coat/winter,	15),
		new /datum/data/vending_product("red coat", /obj/item/clothing/suit/vampire/coat/winter/alt,	15),
		new /datum/data/vending_product("yellow aviators", /obj/item/clothing/glasses/vampire/yellow,	20),
		new /datum/data/vending_product("red aviators", /obj/item/clothing/glasses/vampire/red,	20),
		new /datum/data/vending_product("sunglasses", /obj/item/clothing/glasses/vampire/sun,	20),
		new /datum/data/vending_product("prescription glasses", /obj/item/clothing/glasses/vampire/perception,	20),
		new /datum/data/vending_product("leather gloves", /obj/item/clothing/gloves/vampire/leather,	25),
		new /datum/data/vending_product("rubber gloves", /obj/item/clothing/gloves/vampire/cleaning,	15),
		new /datum/data/vending_product("latex gloves", /obj/item/clothing/gloves/vampire/latex,	5),
		new /datum/data/vending_product("black work gloves", /obj/item/clothing/gloves/vampire/work,	45),
		// CRIMSON EDIT ADD START
		new /datum/data/vending_product("sunglasses", /obj/item/clothing/glasses/sunglasses,	25),
		new /datum/data/vending_product("noir sunglasses", /obj/item/clothing/glasses/sunglasses/noir,	30),
		new /datum/data/vending_product("black gar glasses", /obj/item/clothing/glasses/sunglasses/gar,	85),
		// CRIMSON EDIT ADD END
		new /datum/data/vending_product("bandana", /obj/item/clothing/head/vampire/bandana,	10),
		new /datum/data/vending_product("red bandana", /obj/item/clothing/head/vampire/bandana/red,	10),
		new /datum/data/vending_product("black bandana", /obj/item/clothing/head/vampire/bandana/black,	10),
		new /datum/data/vending_product("baseball cap", /obj/item/clothing/head/vampire/baseballcap, 10),
		new /datum/data/vending_product("ushanka", /obj/item/clothing/head/vampire/ushanka, 20),
		new /datum/data/vending_product("beanie", /obj/item/clothing/head/vampire/beanie,	10),
		new /datum/data/vending_product("black beanie", /obj/item/clothing/head/vampire/beanie/black,	10),
		new /datum/data/vending_product("rough beanie", /obj/item/clothing/head/vampire/beanie/homeless,	10),
		new /datum/data/vending_product("scarf", /obj/item/clothing/neck/vampire/scarf,	10),
		new /datum/data/vending_product("red scarf", /obj/item/clothing/neck/vampire/scarf/red,	10),
		new /datum/data/vending_product("blue scarf", /obj/item/clothing/neck/vampire/scarf/blue,	10),
		new /datum/data/vending_product("green scarf", /obj/item/clothing/neck/vampire/scarf/green,	10),
		new /datum/data/vending_product("white scarf", /obj/item/clothing/neck/vampire/scarf/white,	10),
		new /datum/data/vending_product("gold cross", /obj/item/card/hunter, 30),
		new /datum/data/vending_product("silver cross", /obj/item/card/hunter/silver, 25),
		new /datum/data/vending_product("duffelbag", /obj/item/storage/backpack/duffelbag,	100),
		new /datum/data/vending_product("backpack", /obj/item/storage/backpack, 100),
		new /datum/data/vending_product("satchel", /obj/item/storage/backpack/satchel, 100),
		new /datum/data/vending_product("leather satchel", /obj/item/storage/backpack/satchel/leather, 150),
// CRIMSON EDIT ADD START - Shop Inventories Additions
		new /datum/data/vending_product("wallet", /obj/item/storage/wallet/darkpack, 25),
		new /datum/data/vending_product("cloth", /obj/item/stack/sheet/cloth, 5),
		new /datum/data/vending_product("baggy clothes", /obj/item/clothing/under/vampire/pinkman, 15),
		new /datum/data/vending_product("blue baggy clothes", /obj/item/clothing/under/vampire/pinkman/blue, 15),
		new /datum/data/vending_product("white baggy clothes", /obj/item/clothing/under/vampire/pinkman/white, 15),
		new /datum/data/vending_product("brown baggy clothes", /obj/item/clothing/under/vampire/pinkman/brown, 15),
		new /datum/data/vending_product("bootcut gray jeans", /obj/item/clothing/under/vampire/bootcut_jeans, 15),
		new /datum/data/vending_product("stonewashed bootcut jeans", /obj/item/clothing/under/vampire/bootcut_jeans/stonewashed, 15),
		new /datum/data/vending_product("blue bootcut jeans", /obj/item/clothing/under/vampire/bootcut_jeans/blue, 15),
		new /datum/data/vending_product("gray tripp jeans", /obj/item/clothing/under/vampire/tripp_jeans, 15),
		new /datum/data/vending_product("blue tripp jeans", /obj/item/clothing/under/vampire/tripp_jeans/blue, 15),
		new /datum/data/vending_product("red tripp jeans", /obj/item/clothing/under/vampire/tripp_jeans/red, 15),
		new /datum/data/vending_product("bomber jacket", /obj/item/clothing/suit/vampire/toggled/bomber_jacket, 25),
		new /datum/data/vending_product("inverted bomber jacket", /obj/item/clothing/suit/vampire/toggled/bomber_jacket/inverted, 25),
		new /datum/data/vending_product("plain brown jacket", /obj/item/clothing/suit/vampire/toggled/plain_jacket, 20),
		new /datum/data/vending_product("plain black jacket", /obj/item/clothing/suit/vampire/toggled/plain_jacket/black, 20),
		new /datum/data/vending_product("military jacket", /obj/item/clothing/suit/vampire/toggled/military_jacket, 25),
		new /datum/data/vending_product("harness boots", /obj/item/clothing/shoes/vampire/harness_boots, 30),
		new /datum/data/vending_product("brown harness boots", /obj/item/clothing/shoes/vampire/harness_boots/brown, 30),

// CRIMSON EDIT ADD END - Shop Inventories Additions
	)
